### ISSUE TITLE
wow，niubility！

### ISSUE THREAD

**Issue by debuleilei** [qq456cvb/VoteNet#1]
你好，看到你上传的代码，太开心了，请问有没有相关的结果可以看下？我有个需求是对16线的雷达点进行场景障碍物识别，请问这种方法对稀疏点云是否会奏效呢？您有什么好的建议，请指教，谢谢。

**Comment by qq456cvb** [comment]
根据文章中的方法和我的理解，如果点云太过稀疏，会导致seed个数不够，recall会降低，并且偏移会比较难学，当然具体要看你的点云有多稀疏，还有实验，目前实验还在跑，这个网络对显存要求比较大。

**Comment by debuleilei** [comment]
很抱歉，再打扰一下，我尝试跑training的部分，遇到些问题，
Prepare SUN RGB-D dataset following the instructions of https://github.com/charlesq34/frustum-pointnets/tree/master/sunrgbd, note you only need to run extract_rgbd_data.m
我发现我现在数据集之后，用自己的笔记本跑extract_rgbd_data.m，一开始要加载路径很长时间，然后就报错挂掉了，我查询了下发现时partfor的原因，改成for之后，生成的文件夹里面是空的，我的路径感觉没啥问题，我想请教一下搞定这个数据集的正确方法……
另外跑demo.m时 卡到死，这是和电脑配置有关还是程序的问题呢，头一次用matlab跑数据集相关的demo，显然菜鸟一枚，还请大神多多指教。

**Comment by qq456cvb** [comment]
demo.m卡到死是因为这个脚本会Load巨大的矩阵进入内存，如果你观察的话会注意到内存直接爆; 生成文件夹是空的，证明循环中报错了，他的脚本是用try/catch直接忽视了错误，我建议把try/catch去掉，这样能看到真实的报错。
