### ISSUE TITLE
extract_rgbd_data.m

### ISSUE THREAD

**Issue by goog** [qq456cvb/VoteNet#13]
hello, i have to install a matlab in linux box in order to run **extract_rgbd_data.m**?

**Comment by qq456cvb** [comment]
Yes, this part of code is borrowed from [FrustumNet](https://github.com/charlesq34/frustum-pointnets/blob/master/sunrgbd/sunrgbd_data/matlab/SUNRGBDtoolbox/extract_rgbd_data.m).
