### ISSUE TITLE
Reproduction Result

### ISSUE THREAD

**Issue by jytime** [qq456cvb/VoteNet#2]
Hi thanks for your excellent work.
May I ask what's your evaluation result of the VoteNet? 
I am reproducing BoxNet (the simple version of VoteNet) by Pytorch and the result is far from the BoxNet claimed result (53.0%) in the paper. It would be great if you would like to share the result

Best,
Jianyuan

**Comment by qq456cvb** [comment]
Sorry but I currently do not have much resource to run this code, once I reproduced the result, I will push it here.

**Comment by jytime** [comment]
Thank u

**Comment by timetomakesense** [comment]
hi how are you guys going? I can only achieve 50.8% on sunrgbd under the setting of votenet

**Comment by xudi1227** [comment]
@timetomakesense @jytime  Hi, may I know what kind of GPU you guys are using? Does it really need a Volta Quadro GP100 (as claimed by the author), or 2~4 GTX1080Ti will do?

**Comment by jytime** [comment]
> @timetomakesense @jytime Hi, may I know what kind of GPU you guys are using? Does it really need a Volta Quadro GP100 (as claimed by the author), or 2~4 GTX1080Ti will do?

one is enough
