### ISSUE TITLE
a liite confusing about dis2center in Model.py line 59

### ISSUE THREAD

**Issue by tsbiosky** [qq456cvb/VoteNet#4]
dist2center = tf.abs(tf.expand_dims(seeds_xyz, 2) - tf.expand_dims(bboxes_xyz, 1))
why this could represent the dis2center , i mean tf.expand_dims(seeds_xyz, 2) will be  (x,y,1,z)  and tf.expand_dims(bboxes_xyz, 1)) will be (x,1,y,z) right ?

**Comment by qq456cvb** [comment]
Notice that the last dimension has shape 3 which is x, y, z, so tf.expand_dims(seeds_xyz, 2) will be (B * Ns * 1 * 3) and tf.expand_dims(bboxes_xyz, 1)) will be (B * 1 * Nb * 3), you will get a distance matrix with (B * Ns * Nb * 3) by broadcasting, where the last dimension is the distance along x, y, z axis.
