### ISSUE TITLE
The number of bounding box

### ISSUE THREAD

**Issue by sichance** [qq456cvb/VoteNet#5]
请问一下，每个场景的bounding box的数量是一样的吗，如果不一样的话，bboxes_xyz等变量怎么赋值呢，维度好像会不一致呀

**Comment by qq456cvb** [comment]
不一样的时候会做edge padding，重复的ground truth bbox并不会影响loss，因为我们对于每个proposal找距离它最近的ground truth。

**Comment by sichance** [comment]
非常感谢你的回答，我还有一点不大明白，想请教一下，文章中的K cluster的K要怎么选择，只要选一个比场景中物体个数更大的数就行吗，但是如果场景中的物体数量很不一样，有的十几个物体，有些可能只有两三个，会不会导致多个positive 的proposal逼近的是相同的bounding box，要怎么去除冗余的bounding box呢

**Comment by qq456cvb** [comment]
冗余的bounding box有3D non-maximal-suppression来去除

**Comment by sichance** [comment]
好的，感谢大神指教！
